In [23]:
#Q1
l=[1,2,3,4,5,6,7,8,9,10]
sub_l1=[]
sub_l2=[]
for x in l:
    if x%2==0:
      sub_l1.append(x**2)
    else:
      sub_l2.append(x**3)
        
ls=sub_l1+sub_l2
ls

[4, 16, 36, 64, 100, 1, 27, 125, 343, 729]

In [ ]:
# Q2
# Create a dictionary named “Products” representing at least five entities (products),
# where each entity stores:
#  Prod_Name
#  Prod_Category
#  price

product={}
l=[]
ma=0
mi=0
for i in range(5):
    n=input(f"Enter name for product:{i+1}")
    c=input(f"Write category for product:{i+1}")
    p=float(input(f"Enter price for product:{i+1}"))
    maxx=[n]
    product[i]={
        "Prod_Name ": n,
        "Prod_Category ":c,
        "Price":p}
    l.append(product[i]["Price"])
    ma=l.index(max(l))
    mi=l.index(min(l))
    
print(f"product having max price {product[ma]}")
print(f"product having max price {product[mi]}")
print("sorted by price ",dict(sorted(product.items(),key=lambda x:float(x)[1]["Price"])))


SyntaxError: closing parenthesis '}' does not match opening parenthesis '[' (105842130.py, line 27)

In [60]:
# Q3
from functools import reduce
l=[1,2,3,4,5,6,7,8,9,10]
ev=filter(lambda x:x%2==0,l)
ev=list(ev)
print(f"even numbers {ev}")
ev_sq=map(lambda x:x**2,list(ev))
ev_sq=list(ev_sq)
print(f"even squared numbers {ev_sq}")
total = reduce(lambda x,y:x+y,ev_sq)
print(f"total {total}")

even numbers [2, 4, 6, 8, 10]
even squared numbers [4, 16, 36, 64, 100]
total 220


In [74]:
# Q5
import numpy as np
matrix=np.random.rand(6,4)
print("Shape : ", matrix.shape)
print("Size : ", matrix.size)
print("Dtype : ", matrix.dtype)
print("mean col-wise : ", np.mean(matrix,axis=0))
print("mean row-wise : ", np.mean(matrix,axis=1))
print("Max element index : ", int(np.argmax(matrix)))


Shape :  (6, 4)
Size :  24
Dtype :  float64
mean col-wise :  [0.55424868 0.68785583 0.7412875  0.48315356]
mean row-wise :  [0.72514796 0.74279338 0.51130818 0.50514422 0.66915902 0.5462656 ]
Max element index :  6


In [80]:
#Q6
import numpy as np
arr=np.random.rand(6,4)
avg=np.mean(arr,axis=1)
print("Avg score per system : ",avg )
rnk=np.argsort(arr,axis=1)
print("Ranking :\n",rnk )
t=avg[rnk]
t


Avg score per system :  [0.46477654 0.69267648 0.33765385 0.60958749 0.28592401 0.41957855]
Ranking :
 [[2 3 0 1]
 [0 2 1 3]
 [3 2 1 0]
 [0 2 1 3]
 [3 1 2 0]
 [0 2 3 1]]


array([[0.33765385, 0.60958749, 0.46477654, 0.69267648],
       [0.46477654, 0.33765385, 0.69267648, 0.60958749],
       [0.60958749, 0.33765385, 0.69267648, 0.46477654],
       [0.46477654, 0.33765385, 0.69267648, 0.60958749],
       [0.60958749, 0.69267648, 0.33765385, 0.46477654],
       [0.46477654, 0.33765385, 0.60958749, 0.69267648]])

In [ ]:
#Q7
import numpy as np
arr=np.random.rand(100,3)
m=np.max(arr)
print(f"Normalized array {arr/m}")
print(f"highest variance along column={np.max(np.var(arr,axis=0))}")
print(f"row with max value={np.max(np.sum(arr,axis=1))}")

highest variance along column=0.08308994165950727
row with max value=2.5511453377384083
